collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.707304
color:
  saturation: 0.4269603
  brandStrength: 0.6916628
  lightness: 0.6192266
  brandColors:
    - '#B36631'
    - '#CE925C'
    - '#6F391F'
    - '#556600'
    - '#C97B93'
  rhythmicContrast: 0.6568206
layout_spectrum: 0
name: "Evan's Notebooks"
